-- ==========================================================================
-- A Guantes Negros — datos semilla para Supabase
-- ==========================================================================
-- Generado desde src/data/catalog.ts. Correlo DESPUÉS de schema.sql.
-- Es idempotente: si el slug ya existe, actualiza la fila (upsert), así que
-- podés volver a correrlo para resincronizar el catálogo.
-- ==========================================================================

begin;

-- ---- Categorías ---------------------------------------------------------
insert into public.categories (slug, name, tagline, mascot, art) values
  ('pigmentos', 'Pigmentos', 'Tintas Dynamic, Elephant Klug y Vincent', 'ink', 'ink'),
  ('bioseguridad', 'Productos de Bioseguridad', 'Barbijos, guantes, jabón, campos y film', 'gloves', 'gloves'),
  ('agujas', 'Agujas', 'Agujas y cartuchos, todas las configuraciones', 'pointing', 'cartridge'),
  ('varios', 'Varios', 'Stencil, cables y cuidado post tatuaje', 'hero', 'stencil')
on conflict (slug) do update set
  name = excluded.name, tagline = excluded.tagline,
  mascot = excluded.mascot, art = excluded.art;

-- ---- Productos ----------------------------------------------------------
insert into public.products (slug, name, brand, price, compare_at, category, art, rating, reviews, badge, featured, description, specs, stock) values
  ('dynamic-black-8oz', 'Dynamic Black 8 oz', 'Dynamic', 18990, null, 'pigmentos', 'ink', 5, 203, 'CLÁSICA', true, 'El negro más legendario de la industria. Fluida para líneas, densa para relleno y con una curación que los negros de Dynamic garantizan por décadas. La botella que no puede faltar.', '[["Contenido", "240 ml / 8 oz"], ["Color", "Negro intenso"], ["Origen", "USA"]]'::jsonb, 20),
  ('elephant-klug-1oz', 'Elephant Klug 1 oz', 'Elephant Klug', 4990, null, 'pigmentos', 'ink', 5, 88, null, false, 'Pigmento Elephant Klug en frasco de 1 oz. Negro intenso, curación limpia y tonos bien sostenidos en el tiempo. Ideal para líneas y sombras.', '[["Contenido", "30 ml / 1 oz"], ["Color", "Negro"]]'::jsonb, 20),
  ('elephant-klug-4oz', 'Elephant Klug 4 oz', 'Elephant Klug', 14990, null, 'pigmentos', 'ink', 5, 61, null, false, 'Pigmento Elephant Klug en frasco de 4 oz. Para estudios de alto volumen. Mismo negro profundo, más rendimiento.', '[["Contenido", "120 ml / 4 oz"], ["Color", "Negro"]]'::jsonb, 20),
  ('elephant-klug-8oz', 'Elephant Klug 8 oz', 'Elephant Klug', 24990, null, 'pigmentos', 'ink', 5, 44, 'RENDIDOR', false, 'Pigmento Elephant Klug 8 oz. El formato más económico por ml para estudios que trabajan en serio. Negro profundo, sesión tras sesión.', '[["Contenido", "240 ml / 8 oz"], ["Color", "Negro"]]'::jsonb, 20),
  ('vincent-black-1oz', 'Vincent Black 1 oz', 'Vincent', 5490, null, 'pigmentos', 'ink', 4, 53, null, false, 'Pigmento Vincent Black 1 oz. Negro de alta concentración, viscosidad media y curación uniforme. Una alternativa premium con excelente relación precio-calidad.', '[["Contenido", "30 ml / 1 oz"], ["Color", "Negro"]]'::jsonb, 20),
  ('biomaser-cejas-12ml', 'Biomaser Cejas 12 ml', 'Biomaser', 7990, null, 'pigmentos', 'ink', 5, 39, 'PMU', false, 'Pigmento Biomaser específico para cejas en dermopigmentación. 12 ml de alta concentración, colores calibrados para piel latinoamericana y curación predecible.', '[["Contenido", "12 ml"], ["Uso", "Cejas (dermopigmentación)"], ["Origen", "Biomaser"]]'::jsonb, 20),
  ('guantes-nitrilo-negros-x100', 'Guantes de Nitrilo Negros x100', 'A Guantes Negros', 13990, null, 'bioseguridad', 'gloves', 5, 218, 'LA CASA', true, 'El producto que le da nombre a la casa. Nitrilo negro de alta resistencia, sin látex y con el calce exacto. Caja x100 unidades disponible en S, M, L y XL.', '[["Material", "Nitrilo"], ["Color", "Negro"], ["Cantidad", "Caja x100"], ["Talles", "S / M / L / XL"], ["Libre de látex", "Sí"]]'::jsonb, 20),
  ('film-eco-15m', 'Film Eco 15m', 'A Guantes Negros', 4490, null, 'bioseguridad', 'film', 4, 87, null, false, 'Rollo de film protector de 15 metros para cubrir máquinas, camillas y superficies de trabajo. Higiene total, sesión tras sesión.', '[["Largo", "15 m"], ["Ancho", "30 cm"]]'::jsonb, 20),
  ('cubre-cable-x100', 'Cubre Cable x100', 'A Guantes Negros', 5990, null, 'bioseguridad', 'film', 5, 64, null, false, 'Fundas descartables para clip cord y cables RCA. Caja x100 unidades. Mantené tu estación impecable con cero esfuerzo.', '[["Cantidad", "Caja x100"], ["Material", "Polietileno"], ["Compatibilidad", "Clip cord y RCA"]]'::jsonb, 20),
  ('campos-esteriles-x50', 'Campos Estériles BN x50', 'A Guantes Negros', 6990, null, 'bioseguridad', 'film', 4, 29, null, false, 'Campos estériles descartables para organizar y proteger tu espacio de trabajo. Paquete x50 unidades.', '[["Cantidad", "x50 unidades"], ["Esterilización", "E.O. Gas"]]'::jsonb, 20),
  ('barbijos-descartables-x50', 'Barbijos Descartables x50', 'A Guantes Negros', 3990, null, 'bioseguridad', 'film', 4, 38, null, false, 'Barbijos tricapa descartables para uso en estudio. Paquete x50. Comodidad y protección en cada sesión.', '[["Cantidad", "x50 unidades"], ["Capas", "3 capas"]]'::jsonb, 20),
  ('jabon-antiseptico', 'Jabón Antiséptico', 'A Guantes Negros', 3990, null, 'bioseguridad', 'soap', 5, 64, null, false, 'Jabón antiséptico neutro para limpiar la zona durante y después del tatuaje. pH equilibrado, sin perfumes y sin irritación en piel recién tatuada.', '[["Contenido", "500 ml"], ["pH", "Neutro"], ["Perfume", "Sin perfume"]]'::jsonb, 20),
  ('agujas-1207-rl-x50', 'Agujas 1207 RL x50', 'A Guantes Negros', 3490, null, 'agujas', 'needle', 5, 134, 'MÁS VENDIDAS', true, 'Agujas round liner 7 en blister x50 unidades. Ideales para líneas medianas con precisión constante. Afiladas con laser, esterilizadas con gas EO.', '[["Configuración", "1207 RL"], ["Cantidad", "Blister x50"], ["Esterilización", "E.O. Gas"]]'::jsonb, 20),
  ('agujas-1205-rs-x50', 'Agujas 1205 RS x50', 'A Guantes Negros', 3290, null, 'agujas', 'needle', 5, 98, null, false, 'Round shader 5 en blister x50. Para sombras suaves y trabajo en pequeños detalles. Flujo de tinta constante.', '[["Configuración", "1205 RS"], ["Cantidad", "Blister x50"], ["Esterilización", "E.O. Gas"]]'::jsonb, 20),
  ('agujas-1209-rl-x50', 'Agujas 1209 RL x50', 'A Guantes Negros', 3490, null, 'agujas', 'needle', 5, 77, null, false, 'Round liner 9 en blister x50. Para líneas más gruesas y relleno de detalles. Punta afilada, calidad consistente.', '[["Configuración", "1209 RL"], ["Cantidad", "Blister x50"]]'::jsonb, 20),
  ('agujas-1215-rl-x50', 'Agujas 1215 RL x50', 'A Guantes Negros', 3790, null, 'agujas', 'needle', 4, 45, null, false, 'Round liner 15 en blister x50. Ideales para líneas gruesas y estilos neo-tradicional.', '[["Configuración", "1215 RL"], ["Cantidad", "Blister x50"]]'::jsonb, 20),
  ('agujas-1205-m1-x50', 'Agujas 1205 M1 x50', 'A Guantes Negros', 3490, null, 'agujas', 'needle', 4, 52, null, false, 'Magnum 5 en blister x50. Para color sólido y sombras en áreas pequeñas. Distribución de tinta uniforme.', '[["Configuración", "1205 M1"], ["Cantidad", "Blister x50"]]'::jsonb, 20),
  ('cartuchos-black-sheep-1205rl-x20', 'Black Sheep 1205 RL x20', 'Black Sheep', 9990, null, 'agujas', 'cartridge', 5, 176, 'MÁS VENDIDO', true, 'Cartucho round liner 5 de Black Sheep en caja x20 unidades. Membrana antiretorno de precisión, flujo de tinta estable y aguja afilada con láser. Para líneas finas perfectas.', '[["Configuración", "1205 RL"], ["Cantidad", "Caja x20"], ["Membrana", "Antiretorno"], ["Aguja", "Afilada con láser"]]'::jsonb, 20),
  ('cartuchos-black-sheep-1209rl-x20', 'Black Sheep 1209 RL x20', 'Black Sheep', 9990, null, 'agujas', 'cartridge', 5, 143, null, false, 'Cartucho round liner 9 de Black Sheep, caja x20. Para líneas medianas y gruesas con la consistencia que exige el trabajo profesional.', '[["Configuración", "1209 RL"], ["Cantidad", "Caja x20"], ["Membrana", "Antiretorno"]]'::jsonb, 20),
  ('cartuchos-black-sheep-1215m1-x20', 'Black Sheep 1215 M1 x20', 'Black Sheep', 10990, null, 'agujas', 'cartridge', 4, 67, null, false, 'Cartucho magnum 15 de Black Sheep, caja x20. Para empaquetar color y sombras en áreas grandes. Distribución perfecta.', '[["Configuración", "1215 M1"], ["Cantidad", "Caja x20"]]'::jsonb, 20),
  ('cartuchos-filter-1205rl-x20', 'Filter 1205 RL x20', 'Filter', 8990, null, 'agujas', 'cartridge', 5, 94, null, false, 'Cartucho round liner 5 Filter, caja x20. Membrana de alta precisión y aguja tratada para líneas ultra finas. Muy popular en lettering y fineline.', '[["Configuración", "1205 RL"], ["Cantidad", "Caja x20"], ["Membrana", "Alta precisión"]]'::jsonb, 20),
  ('cartuchos-filter-1207rl-x20', 'Filter 1207 RL x20', 'Filter', 8990, null, 'agujas', 'cartridge', 5, 88, null, false, 'Cartucho round liner 7 Filter, caja x20. Flujo constante, sin saltos ni tapones. Líneas claras y definidas.', '[["Configuración", "1207 RL"], ["Cantidad", "Caja x20"]]'::jsonb, 20),
  ('cartuchos-ez-1205rl-x20', 'EZ Revolution 1205 RL x20', 'EZ Revolution', 11990, null, 'agujas', 'cartridge', 5, 72, 'PRO', false, 'Cartucho EZ Revolution round liner 5, caja x20. Tecnología de punta: aguja soldada a láser, membrana de doble cámara y ajuste perfecto en cualquier pen.', '[["Configuración", "1205 RL"], ["Cantidad", "Caja x20"], ["Membrana", "Doble cámara"], ["Aguja", "Soldada a láser"]]'::jsonb, 20),
  ('cartuchos-ez-1209rl-x20', 'EZ Revolution 1209 RL x20', 'EZ Revolution', 11990, null, 'agujas', 'cartridge', 5, 61, null, false, 'Cartucho EZ Revolution round liner 9, caja x20. Potencia y precisión para cualquier estilo. El preferido de artistas de nivel internacional.', '[["Configuración", "1209 RL"], ["Cantidad", "Caja x20"]]'::jsonb, 20),
  ('butter-tha-thu', 'Butter Tha Thu', 'Butter Tha Thu', 7490, null, 'varios', 'cream', 5, 118, null, true, 'Manteca de cacao natural para el cuidado post-tattoo. Hidratación profunda, recuperación acelerada y negros más intensos. Sin químicos, sin conservantes agresivos.', '[["Base", "Manteca de cacao"], ["Uso", "Post sesión"], ["Conservantes", "Sin parabenos"]]'::jsonb, 20),
  ('crema-post-tattoo', 'Crema Post Tattoo', 'A Guantes Negros', 5990, null, 'varios', 'cream', 4, 76, null, false, 'Crema post-tattoo de la casa: base vegetal, caléndula y manteca de karité. Cicatrización acelerada, menos picazón y colores que se mantienen intensos.', '[["Base", "Vegetal"], ["Activos", "Caléndula + Karité"], ["Uso", "Post sesión"]]'::jsonb, 20),
  ('stencil-original-black', 'Stencil Original Black', 'Stencil Original', 4990, null, 'varios', 'stencil', 5, 89, null, false, 'Papel de transferencia estencial negro. Transferencia nítida, rápido secado y excelente adherencia. Compatible con cualquier solución de stencil.', '[["Color", "Negro"], ["Hojas", "x50"], ["Tipo", "Carbon transfer"]]'::jsonb, 20),
  ('inkplay-stencil', 'Inkplay Stencil', 'Inkplay', 5490, null, 'varios', 'stencil', 5, 102, 'FAVORITO', false, 'Solución de stencil Inkplay. El producto que hace que el stencil aguante toda la sesión: agarre firme, líneas bien definidas y sin corridas.', '[["Contenido", "120 ml"], ["Secado", "60 segundos"]]'::jsonb, 20),
  ('inkplay-foam', 'Inkplay Foam', 'Inkplay', 4490, null, 'varios', 'soap', 4, 58, null, false, 'Espuma limpiadora Inkplay para usar durante la sesión. Neutra, sin fragancia y con activos calmantes para minimizar el estrés en la piel.', '[["Contenido", "200 ml"], ["Tipo", "Espuma"]]'::jsonb, 20),
  ('inkplay-finish-spray', 'Inkplay Finish Spray', 'Inkplay', 4990, null, 'varios', 'soap', 4, 43, null, false, 'Spray de cierre Inkplay para aplicar al finalizar la sesión. Sella la zona, reduce la inflamación y prepara la piel para la cicatrización.', '[["Contenido", "150 ml"], ["Aplicación", "Al finalizar la sesión"]]'::jsonb, 20),
  ('inkplay-witch-hazel', 'Inkplay Witch Hazel', 'Inkplay', 3990, null, 'varios', 'soap', 5, 37, null, false, 'Hamamelis puro Inkplay (Witch Hazel) para limpiar sin irritar. Refrescante, antiséptico y compatible con cualquier tipo de piel.', '[["Contenido", "250 ml"], ["Base", "Hamamelis puro"]]'::jsonb, 20),
  ('piel-sintetica-a4', 'Piel Sintética A4', 'A Guantes Negros', 4990, null, 'varios', 'stencil', 5, 93, 'PRÁCTICA', false, 'Piel sintética formato A4 para práctica de tattoo. Textura y firmeza similares a la piel real. Ideal para alumnos y para probar diseños antes de tatuar.', '[["Tamaño", "A4 (21 x 29.7 cm)"], ["Capas", "Doble capa"], ["Grosor", "4 mm"]]'::jsonb, 20),
  ('cable-rca-clip-cord', 'Cable RCA / Clip Cord', 'A Guantes Negros', 4490, null, 'varios', 'kit', 4, 33, null, false, 'Cable dual RCA y Clip Cord en un solo producto. Blindado, flexible y con conectores bañados en oro para cero pérdida de señal.', '[["Conexión", "RCA y Clip Cord"], ["Largo", "2 m"], ["Conectores", "Bañados en oro"]]'::jsonb, 20),
  ('papel-transfer-atsui', 'Papel Transfer Atsui x50', 'Atsui', 5990, null, 'varios', 'stencil', 5, 67, null, true, 'Papel de transferencia Atsui x50 hojas. Transferencia nítida y duradera en cualquier máquina de copiado. El elegido por tatuadores que no negocian la línea del diseño.', '[["Cantidad", "x50 hojas"], ["Compatibilidad", "Cualquier fotocopiadora/impresora"]]'::jsonb, 20)
on conflict (slug) do update set
  name = excluded.name, brand = excluded.brand, price = excluded.price,
  compare_at = excluded.compare_at, category = excluded.category, art = excluded.art,
  rating = excluded.rating, reviews = excluded.reviews, badge = excluded.badge,
  featured = excluded.featured, description = excluded.description,
  specs = excluded.specs, stock = excluded.stock;

commit;
